In [570]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from datetime import datetime
import json

In [571]:
#current air pollution data
api_key="bcf183f11bc94a8ec008ab3d4049ae88"
url="http://api.openweathermap.org/data/2.5/air_pollution"
param = {
    "lat":28.70405920,
    "lon":77.10249020,
    "appid":api_key
}
data=requests.get(url,params=param)
data=data.json()
print(data)

{'coord': {'lon': 77.1025, 'lat': 28.7041}, 'list': [{'main': {'aqi': 5}, 'components': {'co': 1473.36, 'no': 0, 'no2': 31.81, 'o3': 27.22, 'so2': 3.06, 'pm2_5': 243.83, 'pm10': 278.4, 'nh3': 2.83}, 'dt': 1768589376}]}

In [572]:
start_date=datetime(2022, 1, 1, 0, 0, 0)
unix_start=int(start_date.timestamp())
end_date=datetime(2026,1,16,22,0,0)
unix_end=int(end_date.timestamp())
print(unix_start)
print(unix_end)

1640975400
1768581000

In [573]:
#historical air pollution data
api_key="bcf183f11bc94a8ec008ab3d4049ae88"
url1="https://api.openweathermap.org/data/2.5/air_pollution/history"
param1={
    "lat":28.70405920,
    "lon":77.10249020,
    "start":unix_start,
    "end":unix_end,
    "appid":api_key
}
response1=requests.get(url1,params=param1)
response1.text

'{"coord":{"lon":77.1025,"lat":28.7041},"list":[{"main":{"aqi":5},"components":{"co":2269.74,"no":1.09,"no2":64.43,"o3":7.06,"so2":10.01,"pm2_5":230.56,"pm10":292.91,"nh3":5.64},"dt":1640977200},{"main":{"aqi":5},"components":{"co":1976.01,"no":0.69,"no2":52.78,"o3":7.51,"so2":7.63,"pm2_5":221.76,"pm10":272.03,"nh3":5.07},"dt":1640980800},{"main":{"aqi":5},"components":{"co":1842.5,"no":0.89,"no2":45.24,"o3":5.99,"so2":7.09,"pm2_5":221.3,"pm10":266.47,"nh3":5.26},"dt":1640984400},{"main":{"aqi":5},"components":{"co":1762.39,"no":1.36,"no2":40.1,"o3":4.07,"so2":6.79,"pm2_5":224.94,"pm10":266.86,"nh3":5.64},"dt":1640988000},{"main":{"aqi":5},"components":{"co":1708.98,"no":1.63,"no2":37.01,"o3":3.58,"so2":6.79,"pm2_5":230.35,"pm10":269,"nh3":5.38},"dt":1640991600},{"main":{"aqi":5},"components":{"co":1708.98,"no":1.7,"no2":36.33,"o3":3.98,"so2":7.51,"pm2_5":236.37,"pm10":272.2,"nh3":5.19},"dt":1640995200},{"main":{"aqi":5},"components":{"co":1815.8,"no":2.65,"no2":37.7,"o3":3.76,"so2":9.54,"pm2_5":248.41,"pm10":288.38,"nh3":6.08},"dt":1640998800},{"main":{"aqi":5},"components":{"co":2136.23,"no":8.16,"no2":41.81,"o3":0.97,"so2":13.11,"pm2_5":272.59,"pm10":328.78,"nh3":7.54},"dt":1641002400},{"main":{"aqi":5},"components":{"co":2429.96,"no":16.09,"no2":43.18,"o3":1.97,"so2":15.5,"pm2_5":289.49,"pm10":357.25,"nh3":7.85},"dt":1641006000},{"main":{"aqi":5},"components":{"co":2536.77,"no":22.13,"no2":39.07,"o3":10.55,"so2":18.36,"pm2_5":294.62,"pm10":364.18,"nh3":7.41},"dt":1641009600},{"main":{"aqi":5},"components":{"co":2483.37,"no":20.79,"no2":37.7,"o3":25.39,"so2":19.79,"pm2_5":295.25,"pm10":365.69,"nh3":8.49},"dt":1641013200},{"main":{"aqi":5},"components":{"co":2243.04,"no":13.41,"no2":37.01,"o3":55.07,"so2":19.79,"pm2_5":297.3,"pm10":362.12,"nh3":10.39},"dt":1641016800},{"main":{"aqi":5},"components":{"co":1455.31,"no":1.41,"no2":13.71,"o3":191.69,"so2":21.93,"pm2_5":273.16,"pm10":296.89,"nh3":3.39},"dt":1641020400},{"main":{"aqi":5},"components":{"co":1308.44,"no":0.78,"no2":8.91,"o3":211.72,"so2":18.12,"pm2_5":238.59,"pm10":257.38,"nh3":3.67},"dt":1641024000},{"main":{"aqi":5},"components":{"co":1268.39,"no":0.63,"no2":8.65,"o3":211.72,"so2":16.69,"pm2_5":212.66,"pm10":230.03,"nh3":4.81},"dt":1641027600},{"main":{"aqi":5},"components":{"co":1642.23,"no":1.96,"no2":25.36,"o3":150.2,"so2":17.17,"pm2_5":224.24,"pm10":258.57,"nh3":10.89},"dt":1641031200},{"main":{"aqi":5},"components":{"co":2296.45,"no":3.27,"no2":54.15,"o3":78.68,"so2":19.07,"pm2_5":261.13,"pm10":321.06,"nh3":18.49},"dt":1641034800},{"main":{"aqi":5},"components":{"co":2990.72,"no":1.87,"no2":91.85,"o3":27.54,"so2":25.27,"pm2_5":291.9,"pm10":368.59,"nh3":27.61},"dt":1641038400},{"main":{"aqi":5},"components":{"co":3524.78,"no":5.64,"no2":115.16,"o3":3.08,"so2":32.42,"pm2_5":320.64,"pm10":413.17,"nh3":37.49},"dt":1641042000},{"main":{"aqi":5},"components":{"co":3791.81,"no":12.85,"no2":111.04,"o3":0.41,"so2":30.28,"pm2_5":349.62,"pm10":457.05,"nh3":34.45},"dt":1641045600},{"main":{"aqi":5},"components":{"co":3738.4,"no":11.62,"no2":97.33,"o3":0.86,"so2":23.6,"pm2_5":366.6,"pm10":474.95,"nh3":22.29},"dt":1641049200},{"main":{"aqi":5},"components":{"co":3364.56,"no":2.71,"no2":82.25,"o3":5.5,"so2":17.88,"pm2_5":359,"pm10":451.49,"nh3":12.03},"dt":1641052800},{"main":{"aqi":5},"components":{"co":3391.27,"no":4.92,"no2":74.03,"o3":2.53,"so2":15.5,"pm2_5":369.74,"pm10":465.01,"nh3":9.5},"dt":1641056400},{"main":{"aqi":5},"components":{"co":3257.75,"no":8.49,"no2":66.49,"o3":0.82,"so2":11.8,"pm2_5":364.37,"pm10":454.05,"nh3":7.73},"dt":1641060000},{"main":{"aqi":5},"components":{"co":2937.32,"no":7.6,"no2":58.95,"o3":0.87,"so2":8.11,"pm2_5":344.25,"pm10":414.38,"nh3":5.95},"dt":1641063600},{"main":{"aqi":5},"components":{"co":2563.48,"no":2.99,"no2":52.09,"o3":3.22,"so2":6.85,"pm2_5":332.33,"pm10":387.08,"nh3":5.7},"dt":1641067200},{"main":{"aqi":5},"components":{"co":2269.74,"no":0.49,"no2":42.16,"o3":10.19,"so2":6.26,"pm2_5":330.79,"pm10":375.75,"nh3":5.7},"dt":1641070800},{"main":{"aqi":5},"components":{"co":2082.82,"no":0.09,"no2":33.59,"o3":18.42,"so2":5.96,"pm2_5":336.75,"pm10":374.72,"nh3":5.64},"dt":1641074400},{"main":{"aqi":5},"components":{"co":2002.72,"no":0.06,"no2":29.82,"o3":21.64,"so2":6.14,"pm2_5":346.1,"pm10":381.28,"nh3":5.32},"dt":1641078000},{"main":{"aqi":5},"components":{"co":2002.72,"no":0.09,"no2":29.47,"o3":21.28,"so2":6.85,"pm2_5":354.86,"pm10":389.59,"nh3":5.38},"dt":1641081600},{"main":{"aqi":5},"components":{"co":2056.12,"no":0.31,"no2":32.9,"o3":17.7,"so2":8.58,"pm2_5":364.25,"pm10":404.59,"nh3":6.21},"dt":1641085200},{"main":{"aqi":5},"components":{"co":2323.15,"no":1.55,"no2":42.5,"o3":9.48,"so2":11.68,"pm2_5":380.09,"pm10":434.87,"nh3":7.28},"dt":1641088800},{"main":{"aqi":5},"components":{"co":2510.07,"no":5.48,"no2":47.98,"o3":7.78,"so2":13.47,"pm2_5":381.11,"pm10":444.74,"nh3":7.22},"dt":1641092400},{"main":{"aqi":5},"components":{"co":2563.48,"no":12.74,"no2":41.81,"o3":21.28,"so2":15.74,"pm2_5":373.75,"pm10":439.24,"nh3":6.97},"dt":1641096000},{"main":{"aqi":5},"components":{"co":2563.48,"no":14.53,"no2":39.76,"o3":39.34,"so2":17.64,"pm2_5":369.54,"pm10":437.81,"nh3":8.36},"dt":1641099600},{"main":{"aqi":5},"components":{"co":2429.96,"no":10.95,"no2":39.41,"o3":69.38,"so2":18.84,"pm2_5":365.58,"pm10":431.98,"nh3":10.64},"dt":1641103200},{"main":{"aqi":5},"components":{"co":1361.85,"no":1.9,"no2":16.96,"o3":183.11,"so2":26.46,"pm2_5":243.71,"pm10":266.72,"nh3":2.53},"dt":1641106800},{"main":{"aqi":5},"components":{"co":1188.28,"no":1.05,"no2":11.31,"o3":205.99,"so2":23.6,"pm2_5":219.74,"pm10":237.85,"nh3":2.37},"dt":1641110400},{"main":{"aqi":5},"components":{"co":1174.93,"no":0.79,"no2":10.11,"o3":214.58,"so2":22.17,"pm2_5":217.63,"pm10":235.03,"nh3":3.39},"dt":1641114000},{"main":{"aqi":5},"components":{"co":1602.17,"no":2.18,"no2":25.7,"o3":155.93,"so2":20.5,"pm2_5":242,"pm10":276.63,"nh3":9.75},"dt":1641117600},{"main":{"aqi":5},"components":{"co":2243.04,"no":3.55,"no2":52.78,"o3":83.68,"so2":20.27,"pm2_5":279.67,"pm10":338.53,"nh3":17.73},"dt":1641121200},{"main":{"aqi":5},"components":{"co":2803.8,"no":1.84,"no2":86.37,"o3":30.04,"so2":23.84,"pm2_5":303.47,"pm10":378.17,"nh3":26.35},"dt":1641124800},{"main":{"aqi":5},"components":{"co":3124.24,"no":4.86,"no2":104.19,"o3":3.49,"so2":26.94,"pm2_5":322.96,"pm10":411.65,"nh3":33.94},"dt":1641128400},{"main":{"aqi":5},"components":{"co":3204.35,"no":10.06,"no2":95.96,"o3":0.72,"so2":22.65,"pm2_5":343.26,"pm10":444.05,"nh3":27.11},"dt":1641132000},{"main":{"aqi":5},"components":{"co":2990.72,"no":5.2,"no2":83.63,"o3":5.63,"so2":16.93,"pm2_5":349.28,"pm10":443.56,"nh3":15.71},"dt":1641135600},{"main":{"aqi":5},"components":{"co":2429.96,"no":0.02,"no2":57.58,"o3":34.33,"so2":13.47,"pm2_5":320.77,"pm10":391.75,"nh3":9.75},"dt":1641139200},{"main":{"aqi":5},"components":{"co":2456.67,"no":0.16,"no2":54.84,"o3":21.46,"so2":12.4,"pm2_5":325.01,"pm10":403.42,"nh3":8.49},"dt":1641142800},{"main":{"aqi":5},"components":{"co":2349.85,"no":0.64,"no2":52.09,"o3":10.91,"so2":9.89,"pm2_5":313.97,"pm10":389.57,"nh3":7.54},"dt":1641146400},{"main":{"aqi":5},"components":{"co":2136.23,"no":1.16,"no2":46.61,"o3":6.62,"so2":7.75,"pm2_5":293.96,"pm10":354.64,"nh3":6.84},"dt":1641150000},{"main":{"aqi":5},"components":{"co":2056.12,"no":1.93,"no2":42.84,"o3":3.84,"so2":8.58,"pm2_5":288.04,"pm10":342.65,"nh3":7.22},"dt":1641153600},{"main":{"aqi":5},"components":{"co":2002.72,"no":2.46,"no2":39.41,"o3":2.66,"so2":8.82,"pm2_5":287.73,"pm10":340,"nh3":7.28},"dt":1641157200},{"main":{"aqi":5},"components":{"co":1949.31,"no":2.54,"no2":35.99,"o3":2.55,"so2":8.46,"pm2_5":286.43,"pm10":336.35,"nh3":7.16},"dt":1641160800},{"main":{"aqi":5},"components":{"co":1922.61,"no":2.4,"no2":33.59,"o3":2.91,"so2":8.23,"pm2_5":288.78,"pm10":335.89,"nh3":6.4},"dt":1641164400},{"main":{"aqi":5},"components":{"co":1976.01,"no":2.37,"no2":33.59,"o3":3.44,"so2":8.7,"pm2_5":295.2,"pm10":339.5,"nh3":6.02},"dt":1641168000},{"main":{"aqi":5},"components":{"co":2136.23,"no":3.69,"no2":35.99,"o3":3.13,"so2":10.73,"pm2_5":309.88,"pm10":358.36,"nh3":7.09},"dt":1641171600},{"main":{"aqi":5},"components":{"co":2563.48,"no":11.62,"no2":40.44,"o3":0.48,"so2":14.78,"pm2_5":338.63,"pm10":406.66,"nh3":8.87},"dt":1641175200},{"main":{"aqi":5},"components":{"co":2910.61,"no":21.01,"no2":42.16,"o3":2.19,"so2":17.17,"pm2_5":354.56,"pm10":434.68,"nh3":9.37},"dt":1641178800},{"main":{"aqi":5},"components":{"co":2857.21,"no":21.46,"no2":41.81,"o3":15.2,"so2":19.07,"pm2_5":348.89,"pm10":425.28,"nh3":9.63},"dt":1641182400},{"main":{"aqi":5},"components":{"co":2857.21,"no":20.79,"no2":42.84,"o3":32.9,"so2":21.93,"pm2_5":351.85,"pm10":432.9,"nh3":11.78},"dt":1641186000},{"main":{"aqi":5},"components":{"co":2670.29,"no":14.31,"no2":43.87,"o3":65.09,"so2":24.32,"pm2_5":347.85,"pm10":425.18,"nh3":14.44},"dt":1641189600},{"main":{"aqi":5},"components":{"co":1388.55,"no":4.02,"no2":25.02,"o3":141.62,"so2":33.38,"pm2_5":191.29,"pm10":222.05,"nh3":9.37},"dt":1641193200},{"main":{"aqi":5},"components":{"co":1108.17,"no":2.74,"no2":19.19,"o3":154.5,"so2":30.52,"pm2_5":138.94,"pm10":162.25,"nh3":8.99},"dt":1641196800},{"main":{"aqi":5},"components":{"co":947.95,"no":2.04,"no2":16.45,"o3":155.93,"so2":26.7,"pm2_5":119.49,"pm10":139.54,"nh3":9.12},"dt":1641200400},{"main":{"aqi":5},"components":{"co":1174.93,"no":3.02,"no2":25.7,"o3":127.32,"so2":23.6,"pm2_5":129.99,"pm10":161.22,"nh3":12.67},"dt":1641204000},{"main":{"aqi":5},"components":{"co":1789.09,"no":4.47,"no2":48.67,"o3":80.11,"so2":23.84,"pm2_5":160.64,"pm10":211.43,"nh3":18.49},"dt":1641207600},{"main":{"aqi":5},"components":{"co":2429.96,"no":2.54,"no2":80.88,"o3":31.47,"so2":25.51,"pm2_5":193.28,"pm10":257.57,"nh3":24.07},"dt":1641211200},{"main":{"aqi":5},"components":{"co":2937.32,"no":3.86,"no2":97.33,"o3":4.78,"so2":26.23,"pm2_5":226.91,"pm10":304.24,"nh3":25.33},"dt":1641214800},{"main":{"aqi":5},"components":{"co":3150.94,"no":8.16,"no2":90.48,"o3":1.35,"so2":25.51,"pm2_5":258.82,"pm10":353.85,"nh3":21.53},"dt":1641218400},{"main":{"aqi":5},"components":{"co":3204.35,"no":9.28,"no2":82.25,"o3":0.95,"so2":23.37,"pm2_5":287.6,"pm10":393.81,"nh3":16.21},"dt":1641222000},{"main":{"aqi":5},"components":{"co":3417.97,"no":13.97,"no2":74.71,"o3":0.32,"so2":21.93,"pm2_5":326.79,"pm10":445.11,"nh3":13.3},"dt":1641225600},{"main":{"aqi":5},"components":{"co":3791.81,"no":24.14,"no2":66.49,"o3":0.02,"so2":21.22,"pm2_5":369.5,"pm10":503.65,"nh3":12.79},"dt":1641229200},{"main":{"aqi":5},"components":{"co":3738.4,"no":27.94,"no2":59.63,"o3":0.01,"so2":17.17,"pm2_5":376.67,"pm10":505.22,"nh3":11.02},"dt":1641232800},{"main":{"aqi":5},"components":{"co":3364.56,"no":25.7,"no2":52.09,"o3":0.01,"so2":12.52,"pm2_5":358.17,"pm10":458.79,"nh3":8.61},"dt":1641236400},{"main":{"aqi":5},"components":{"co":3044.13,"no":21.9,"no2":44.55,"o3":0.01,"so2":11.68,"pm2_5":348.15,"pm10":429.2,"nh3":8.61},"dt":1641240000},{"main":{"aqi":5},"components":{"co":2830.51,"no":19.22,"no2":38.73,"o3":0.02,"so2":11.92,"pm2_5":345.38,"pm10":417.12,"nh3":9.37},"dt":1641243600},{"main":{"aqi":5},"components":{"co":2643.59,"no":17.21,"no2":33.93,"o3":0.02,"so2":12.52,"pm2_5":340.98,"pm10":408.99,"nh3":10.64},"dt":1641247200},{"main":{"aqi":5},"components":{"co":2590.18,"no":17.66,"no2":30.85,"o3":0.02,"so2":13.59,"pm2_5":341.05,"pm10":408.12,"nh3":11.65},"dt":1641250800},{"main":{"aqi":5},"components":{"co":2670.29,"no":21.9,"no2":28.79,"o3":0.01,"so2":16.21,"pm2_5":350.6,"pm10":423.27,"nh3":13.3},"dt":1641254400},{"main":{"aqi":5},"components":{"co":3017.43,"no":33.08,"no2":27.08,"o3":0,"so2":20.27,"pm2_5":377.38,"pm10":467.77,"nh3":15.71},"dt":1641258000},{"main":{"aqi":5},"components":{"co":4005.43,"no":60.8,"no2":26.39,"o3":0,"so2":23.84,"pm2_5":438.37,"pm10":567.02,"nh3":14.57},"dt":1641261600},{"main":{"aqi":5},"components":{"co":5126.95,"no":95.67,"no2":29.13,"o3":0.37,"so2":24.32,"pm2_5":496.59,"pm10":647.69,"nh3":11.4},"dt":1641265200},{"main":{"aqi":5},"components":{"co":4432.68,"no":62.58,"no2":51.41,"o3":7.06,"so2":27.66,"pm2_5":432.57,"pm10":535.45,"nh3":11.78},"dt":1641268800},{"main":{"aqi":5},"components":{"co":4753.11,"no":50.07,"no2":71.97,"o3":24.32,"so2":30.99,"pm2_5":462.11,"pm10":572.65,"nh3":14.57},"dt":1641272400},{"main":{"aqi":5},"components":{"co":4432.68,"no":23.92,"no2":82.25,"o3":75.82,"so2":32.9,"pm2_5":465.64,"pm10":570.92,"nh3":16.47},"dt":1641276000},{"main":{"aqi":5},"components":{"co":1642.23,"no":4.69,"no2":34.96,"o3":150.2,"so2":43.39,"pm2_5":202.73,"pm10":239.25,"nh3":7.28},"dt":1641279600},{"main":{"aqi":5},"components":{"co":1348.5,"no":2.99,"no2":30.16,"o3":160.22,"so2":44.35,"pm2_5":181.53,"pm10":212.74,"nh3":8.11},"dt":1641283200},{"main":{"aqi":5},"components":{"co":1281.74,"no":1.9,"no2":30.16,"o3":161.65,"so2":43.87,"pm2_5":174.96,"pm10":207.29,"nh3":9.88},"dt":1641286800},{"main":{"aqi":5},"components":{"co":1695.63,"no":1.65,"no2":46.61,"o3":110.15,"so2":35.76,"pm2_5":193.17,"pm10":248.7,"nh3":16.47},"dt":1641290400},{"main":{"aqi":5},"components":{"co":2403.26,"no":2.18,"no2":74.71,"o3":42.56,"so2":30.99,"pm2_5":234.29,"pm10":323.7,"nh3":24.57},"dt":1641294000},{"main":{"aqi":5},"components":{"co":3044.13,"no":12.85,"no2":91.85,"o3":3.22,"so2":32.42,"pm2_5":275.84,"pm10":394.05,"nh3":32.42},"dt":1641297600},{"main":{"aqi":5},"components":{"co":3311.16,"no":30.85,"no2":83.63,"o3":0.01,"so2":36.24,"pm2_5":315.07,"pm10":458.36,"nh3":43.06},"dt":1641301200},{"main":{"aqi":5},"components":{"co":3471.37,"no":37.1,"no2":77.46,"o3":0,"so2":40.53,"pm2_5":358.04,"pm10":531.05,"nh3":51.68},"dt":1641304800},{"main":{"aqi":5},"components":{"co":3738.4,"no":39.34,"no2":71.29,"o3":0,"so2":42.92,"pm2_5":397.01,"pm10":599.73,"nh3":54.21},"dt":1641308400},{"main":{"aqi":5},"components":{"co":3898.62,"no":38.44,"no2":63.75,"o3":0,"so2":42.44,"pm2_5":428.83,"pm10":655.63,"nh3":52.18},"dt":1641312000},{"main":{"aqi":5},"components":{"co":3898.62,"no":37.1,"no2":55.52,"o3":0,"so2":39.1,"pm2_5":436.16,"pm10":668.34,"nh3":48.13},"dt":1641315600},{"main":{"aqi":5},"components":{"co":3524.78,"no":32.63,"no2":49.35,"o3":0,"so2":31.47,"pm2_5":409.62,"pm10":613.54,"nh3":40.53},"dt":1641319200},{"main":{"aqi":5},"components":{"co":3070.83,"no":26.15,"no2":46.61,"o3":0.01,"so2":23.37,"pm2_5":378.07,"pm10":533.27,"nh3":32.17},"dt":1641322800},{"main":{"aqi":5},"components":{"co":2937.32,"no":21.9,"no2":43.53,"o3":0.01,"so2":20.5,"pm2_5":376.04,"pm10":503.1,"nh3":26.09},"dt":1641326400},{"main":{"aqi":5},"components":{"co":2910.61,"no":19.67,"no2":40.1,"o3":0.01,"so2":19.07,"pm2_5":388.14,"pm10":500.2,"nh3":20.01},"dt":1641330000},{"main":{"aqi":5},"components":{"co":3017.43,"no":20.56,"no2":37.01,"o3":0.01,"so2":18.84,"pm2_5":409.34,"pm10":512.96,"nh3":15.58},"dt":1641333600},{"main":{"aqi":5},"components":{"co":3337.86,"no":26.6,"no2":36.67,"o3":0,"so2":22.65,"pm2_5":443.55,"pm10":542.53,"nh3":14.69},"dt":1641337200},{"main":{"aqi":5},"components":{"co":4005.43,"no":40.68,"no2":39.07,"o3":0,"so2":29.8,"pm2_5":502.77,"pm10":600.91,"nh3":15.83},"dt":1641340800},{"main":{"aqi":5},"components":{"co":4859.92,"no":60.8,"no2":41.47,"o3":0,"so2":35.76,"pm2_5":572.13,"pm10":673.2,"nh3":16.97},"dt":1641344400},{"main":{"aqi":5},"components":{"co":6088.26,"no":95.67,"no2":42.5,"o3":0,"so2":39.58,"pm2_5":663.8,"pm10":791.06,"nh3":18.49},"dt":1641348000},{"main":{"aqi":5},"components":{"co":7156.37,"no":132.32,"no2":43.18,"o3":0.06,"so2":39.1,"pm2_5":727.04,"pm10":880.46,"nh3":15.83},"dt":1641351600},{"main":{"aqi":5},"components":{"co":5607.6,"no":88.51,"no2":63.06,"o3":1.15,"so2":57.22,"pm2_5":622.59,"pm10":728.62,"nh3":10.51},"dt":1641355200},{"main":{"aqi":5},"components":{"co":5233.76,"no":72.42,"no2":75.4,"o3":3.93,"so2":63.9,"pm2_5":613.14,"pm10":710.73,"nh3":9.37},"dt":1641358800},{"main":{"aqi":5},"components":{"co":4539.49,"no":47.39,"no2":87.74,"o3":11.18,"so2":75.34,"pm2_5":600.48,"pm10":685.85,"nh3":6.4},"dt":1641362400},{"main":{"aqi":5},"components":{"co":3471.37,"no":28.61,"no2":106.93,"o3":25.39,"so2":119.21,"pm2_5":562.28,"pm10":617.67,"nh3":0.38},"dt":1641366000},{"main":{"aqi":5},"components":{"co":3257.75,"no":26.82,"no2":115.16,"o3":29.33,"so2":127.79,"pm2_5":540.7,"pm10":584.28,"nh3":0.21},"dt":1641369600},{"main":{"aqi":5},"components":{"co":3017.43,"no":24.81,"no2":119.27,"o3":24.68,"so2":135.42,"pm2_5":490.49,"pm10":523.24,"nh3":0.27},"dt":1641373200},{"main":{"aqi":5},"components":{"co":2510.07,"no":14.53,"no2":113.79,"o3":17.7,"so2":129.7,"pm2_5":401.11,"pm10":423.79,"nh3":0.37},"dt":1641376800},{"main":{"aqi":5},"components":{"co":2269.74,"no":5.2,"no2":100.08,"o3":16.27,"so2":103,"pm2_5":345.04,"pm10":364.42,"nh3":1.61},"dt":1641380400},{"main":{"aqi":5},"components":{"co":2216.34,"no":0.84,"no2":84.31,"o3":18.24,"so2":79.15,"pm2_5":324.55,"pm10":343.45,"nh3":3.26},"dt":1641384000},{"main":{"aqi":5},"components":{"co":2029.42,"no":0.05,"no2":61.69,"o3":28.61,"so2":54.84,"pm2_5":300.21,"pm10":319.8,"nh3":4.24},"dt":1641387600},{"main":{"aqi":5},"components":{"co":1869.2,"no":0.01,"no2":47.98,"o3":38.27,"so2":41.96,"pm2_5":263.31,"pm10":283.82,"nh3":5.26},"dt":1641391200},{"main":{"aqi":5},"components":{"co":1735.69,"no":0,"no2":42.16,"o3":44.35,"so2":39.1,"pm2_5":229.74,"pm10":249.78,"nh3":5.64},"dt":1641394800},{"main":{"aqi":5},"components":{"co":1668.93,"no":0,"no2":39.41,"o3":48.64,"so2":40.05,"pm2_5":212.85,"pm10":231.48,"nh3":5.51},"dt":1641398400},{"main":{"aqi":5},"components":{"co":1708.98,"no":0,"no2":39.76,"o3":47.92,"so2":41.01,"pm2_5":214.72,"pm10":232.89,"nh3":5.51},"dt":1641402000},{"main":{"aqi":5},"components":{"co":1708.98,"no":0,"no2":41.13,"o3":44.7,"so2":42.92,"pm2_5":212.37,"pm10":227.74,"nh3":4.75},"dt":1641405600},{"main":{"aqi":5},"components":{"co":1588.82,"no":0,"no2":41.13,"o3":42.92,"so2":41.96,"pm2_5":198.95,"pm10":211.53,"nh3":4.24},"dt":1641409200},{"main":{"aqi":5},"components":{"co":1308.44,"no":0,"no2":36.33,"o3":44.35,"so2":38.62,"pm2_5":156.71,"pm10":167.78,"nh3":4.12},"dt":1641412800},{"main":{"aqi":5},"components":{"co":988.01,"no":0,"no2":30.85,"o3":46.49,"so2":35.76,"pm2_5":103.8,"pm10":113.24,"nh3":3.93},"dt":1641416400},{"main":{"aqi":5},"components":{"co":794.41,"no":0,"no2":28.45,"o3":46.49,"so2":34.33,"pm2_5":71.32,"pm10":80.41,"nh3":3.89},"dt":1641420000},{"main":{"aqi":5},"components":{"co":747.68,"no":0,"no2":27.42,"o3":44.7,"so2":31.95,"pm2_5":61.29,"pm10":71.08,"nh3":4.05},"dt":1641423600},{"main":{"aqi":5},"components":{"co":781.06,"no":0,"no2":27.42,"o3":43.63,"so2":30.04,"pm2_5":66.45,"pm10":77.51,"nh3":4.37},"dt":1641427200},{"main":{"aqi":5},"components":{"co":961.3,"no":0,"no2":27.76,"o3":43.63,"so2":27.66,"pm2_5":98.96,"pm10":113.4,"nh3":5},"dt":1641430800},{"main":{"aqi":5},"components":{"co":1335.14,"no":0.01,"no2":32.56,"o3":38.62,"so2":29.8,"pm2_5":160.79,"pm10":182.45,"nh3":6.4},"dt":1641434400},{"main":{"aqi":5},"components":{"co":1655.58,"no":0.29,"no2":38.73,"o3":31.83,"so2":34.81,"pm2_5":216.05,"pm10":243.06,"nh3":7.22},"dt":1641438000},{"main":{"aqi":5},"components":{"co":1735.69,"no":2.79,"no2":41.47,"o3":32.19,"so2":47.21,"pm2_5":237.29,"pm10":263.84,"nh3":7.66},"dt":1641441600},{"main":{"aqi":5},"components":{"co":1682.28,"no":6.59,"no2":42.84,"o3":34.69,"so2":61.99,"pm2_5":227.14,"pm10":252.52,"nh3":8.99},"dt":1641445200},{"main":{"aqi":5},"components":{"co":1495.36,"no":8.94,"no2":43.87,"o3":40.05,"so2":77.25,"pm2_5":196.47,"pm10":217.89,"nh3":9.63},"dt":1641448800},{"main":{"aqi":5},"components":{"co":961.3,"no":5.76,"no2":43.18,"o3":53.64,"so2":84.88,"pm2_5":118.48,"pm10":130.01,"nh3":6.02},"dt":1641452400},{"main":{"aqi":5},"components":{"co":847.82,"no":3.69,"no2":45.93,"o3":60.08,"so2":83.92,"pm2_5":102.63,"pm10":112.3,"nh3":5.7},"dt":1641456000},{"main":{"aqi":5},"components":{"co":854.49,"no":2.1,"no2":52.09,"o3":62.23,"so2":87.74,"pm2_5":106.21,"pm10":116.45,"nh3":6.4},"dt":1641459600},{"main":{"aqi":5},"components":{"co":1602.17,"no":4.08,"no2":78.83,"o3":24.68,"so2":73.43,"pm2_5":146.19,"pm10":176.46,"nh3":

In [574]:
data=response1.text
data1=json.loads(data)

In [575]:
data1

{'coord': {'lon': 77.1025, 'lat': 28.7041},
 'list': [{'main': {'aqi': 5},
   'components': {'co': 2269.74,
    'no': 1.09,
    'no2': 64.43,
    'o3': 7.06,
    'so2': 10.01,
    'pm2_5': 230.56,
    'pm10': 292.91,
    'nh3': 5.64},
   'dt': 1640977200},
  {'main': {'aqi': 5},
   'components': {'co': 1976.01,
    'no': 0.69,
    'no2': 52.78,
    'o3': 7.51,
    'so2': 7.63,
    'pm2_5': 221.76,
    'pm10': 272.03,
    'nh3': 5.07},
   'dt': 1640980800},
  {'main': {'aqi': 5},
   'components': {'co': 1842.5,
    'no': 0.89,
    'no2': 45.24,
    'o3': 5.99,
    'so2': 7.09,
    'pm2_5': 221.3,
    'pm10': 266.47,
    'nh3': 5.26},
   'dt': 1640984400},
  {'main': {'aqi': 5},
   'components': {'co': 1762.39,
    'no': 1.36,
    'no2': 40.1,
    'o3': 4.07,
    'so2': 6.79,
    'pm2_5': 224.94,
    'pm10': 266.86,
    'nh3': 5.64},
   'dt': 1640988000},
  {'main': {'aqi': 5},
   'components': {'co': 1708.98,
    'no': 1.63,
    'no2': 37.01,
    'o3': 3.58,
    'so2': 6.79,
    'pm2_5': 230.35,
    'pm10': 269,
    'nh3': 5.38},
   'dt': 1640991600},
  {'main': {'aqi': 5},
   'components': {'co': 1708.98,
    'no': 1.7,
    'no2': 36.33,
    'o3': 3.98,
    'so2': 7.51,
    'pm2_5': 236.37,
    'pm10': 272.2,
    'nh3': 5.19},
   'dt': 1640995200},
  {'main': {'aqi': 5},
   'components': {'co': 1815.8,
    'no': 2.65,
    'no2': 37.7,
    'o3': 3.76,
    'so2': 9.54,
    'pm2_5': 248.41,
    'pm10': 288.38,
    'nh3': 6.08},
   'dt': 1640998800},
  {'main': {'aqi': 5},
   'components': {'co': 2136.23,
    'no': 8.16,
    'no2': 41.81,
    'o3': 0.97,
    'so2': 13.11,
    'pm2_5': 272.59,
    'pm10': 328.78,
    'nh3': 7.54},
   'dt': 1641002400},
  {'main': {'aqi': 5},
   'components': {'co': 2429.96,
    'no': 16.09,
    'no2': 43.18,
    'o3': 1.97,
    'so2': 15.5,
    'pm2_5': 289.49,
    'pm10': 357.25,
    'nh3': 7.85},
   'dt': 1641006000},
  {'main': {'aqi': 5},
   'components': {'co': 2536.77,
    'no': 22.13,
    'no2': 39.07,
    'o3': 10.55,
    'so2': 18.36,
    'pm2_5': 294.62,
    'pm10': 364.18,
    'nh3': 7.41},
   'dt': 1641009600},
  {'main': {'aqi': 5},
   'components': {'co': 2483.37,
    'no': 20.79,
    'no2': 37.7,
    'o3': 25.39,
    'so2': 19.79,
    'pm2_5': 295.25,
    'pm10': 365.69,
    'nh3': 8.49},
   'dt': 1641013200},
  {'main': {'aqi': 5},
   'components': {'co': 2243.04,
    'no': 13.41,
    'no2': 37.01,
    'o3': 55.07,
    'so2': 19.79,
    'pm2_5': 297.3,
    'pm10': 362.12,
    'nh3': 10.39},
   'dt': 1641016800},
  {'main': {'aqi': 5},
   'components': {'co': 1455.31,
    'no': 1.41,
    'no2': 13.71,
    'o3': 191.69,
    'so2': 21.93,
    'pm2_5': 273.16,
    'pm10': 296.89,
    'nh3': 3.39},
   'dt': 1641020400},
  {'main': {'aqi': 5},
   'components': {'co': 1308.44,
    'no': 0.78,
    'no2': 8.91,
    'o3': 211.72,
    'so2': 18.12,
    'pm2_5': 238.59,
    'pm10': 257.38,
    'nh3': 3.67},
   'dt': 1641024000},
  {'main': {'aqi': 5},
   'components': {'co': 1268.39,
    'no': 0.63,
    'no2': 8.65,
    'o3': 211.72,
    'so2': 16.69,
    'pm2_5': 212.66,
    'pm10': 230.03,
    'nh3': 4.81},
   'dt': 1641027600},
  {'main': {'aqi': 5},
   'components': {'co': 1642.23,
    'no': 1.96,
    'no2': 25.36,
    'o3': 150.2,
    'so2': 17.17,
    'pm2_5': 224.24,
    'pm10': 258.57,
    'nh3': 10.89},
   'dt': 1641031200},
  {'main': {'aqi': 5},
   'components': {'co': 2296.45,
    'no': 3.27,
    'no2': 54.15,
    'o3': 78.68,
    'so2': 19.07,
    'pm2_5': 261.13,
    'pm10': 321.06,
    'nh3': 18.49},
   'dt': 1641034800},
  {'main': {'aqi': 5},
   'components': {'co': 2990.72,
    'no': 1.87,
    'no2': 91.85,
    'o3': 27.54,
    'so2': 25.27,
    'pm2_5': 291.9,
    'pm10': 368.59,
    'nh3': 27.61},
   'dt': 1641038400},
  {'main': {'aqi': 5},
   'components': {'co': 3524.78,
    'no': 5.64,
    'no2': 115.16,
    'o3': 3.08,
    'so2': 32.42,
    'pm2_5': 320.64,
    'pm10': 413.17,
    'nh3': 37.49},
   'dt': 1641042000},
  {'main': {'aqi': 5},
   'components': {'co': 3791.81,
    'no': 12.85,
    'no2': 111.04,
    'o3': 0.41,
    'so2': 30.28,
    'pm2_5': 349.62,
    'pm10': 457.05,
    'nh3': 34.45},
   'dt': 1641045600},
  {'main': {'aqi': 5},
   'components': {'co': 3738.4,
    'no': 11.62,
    'no2': 97.33,
    'o3': 0.86,
    'so2': 23.6,
    'pm2_5': 366.6,
    'pm10': 474.95,
    'nh3': 22.29},
   'dt': 1641049200},
  {'main': {'aqi': 5},
   'components': {'co': 3364.56,
    'no': 2.71,
    'no2': 82.25,
    'o3': 5.5,
    'so2': 17.88,
    'pm2_5': 359,
    'pm10': 451.49,
    'nh3': 12.03},
   'dt': 1641052800},
  {'main': {'aqi': 5},
   'components': {'co': 3391.27,
    'no': 4.92,
    'no2': 74.03,
    'o3': 2.53,
    'so2': 15.5,
    'pm2_5': 369.74,
    'pm10': 465.01,
    'nh3': 9.5},
   'dt': 1641056400},
  {'main': {'aqi': 5},
   'components': {'co': 3257.75,
    'no': 8.49,
    'no2': 66.49,
    'o3': 0.82,
    'so2': 11.8,
    'pm2_5': 364.37,
    'pm10': 454.05,
    'nh3': 7.73},
   'dt': 1641060000},
  {'main': {'aqi': 5},
   'components': {'co': 2937.32,
    'no': 7.6,
    'no2': 58.95,
    'o3': 0.87,
    'so2': 8.11,
    'pm2_5': 344.25,
    'pm10': 414.38,
    'nh3': 5.95},
   'dt': 1641063600},
  {'main': {'aqi': 5},
   'components': {'co': 2563.48,
    'no': 2.99,
    'no2': 52.09,
    'o3': 3.22,
    'so2': 6.85,
    'pm2_5': 332.33,
    'pm10': 387.08,
    'nh3': 5.7},
   'dt': 1641067200},
  {'main': {'aqi': 5},
   'components': {'co': 2269.74,
    'no': 0.49,
    'no2': 42.16,
    'o3': 10.19,
    'so2': 6.26,
    'pm2_5': 330.79,
    'pm10': 375.75,
    'nh3': 5.7},
   'dt': 1641070800},
  {'main': {'aqi': 5},
   'components': {'co': 2082.82,
    'no': 0.09,
    'no2': 33.59,
    'o3': 18.42,
    'so2': 5.96,
    'pm2_5': 336.75,
    'pm10': 374.72,
    'nh3': 5.64},
   'dt': 1641074400},
  {'main': {'aqi': 5},
   'components': {'co': 2002.72,
    'no': 0.06,
    'no2': 29.82,
    'o3': 21.64,
    'so2': 6.14,
    'pm2_5': 346.1,
    'pm10': 381.28,
    'nh3': 5.32},
   'dt': 1641078000},
  {'main': {'aqi': 5},
   'components': {'co': 2002.72,
    'no': 0.09,
    'no2': 29.47,
    'o3': 21.28,
    'so2': 6.85,
    'pm2_5': 354.86,
    'pm10': 389.59,
    'nh3': 5.38},
   'dt': 1641081600},
  {'main': {'aqi': 5},
   'components': {'co': 2056.12,
    'no': 0.31,
    'no2': 32.9,
    'o3': 17.7,
    'so2': 8.58,
    'pm2_5': 364.25,
    'pm10': 404.59,
    'nh3': 6.21},
   'dt': 1641085200},
  {'main': {'aqi': 5},
   'components': {'co': 2323.15,
    'no': 1.55,
    'no2': 42.5,
    'o3': 9.48,
    'so2': 11.68,
    'pm2_5': 380.09,
    'pm10': 434.87,
    'nh3': 7.28},
   'dt': 1641088800},
  {'main': {'aqi': 5},
   'components': {'co': 2510.07,
    'no': 5.48,
    'no2': 47.98,
    'o3': 7.78,
    'so2': 13.47,
    'pm2_5': 381.11,
    'pm10': 444.74,
    'nh3': 7.22},
   'dt': 1641092400},
  {'main': {'aqi': 5},
   'components': {'co': 2563.48,
    'no': 12.74,
    'no2': 41.81,
    'o3': 21.28,
    'so2': 15.74,
    'pm2_5': 373.75,
    'pm10': 439.24,
    'nh3': 6.97},
   'dt': 1641096000},
  {'main': {'aqi': 5},
   'components': {'co': 2563.48,
    'no': 14.53,
    'no2': 39.76,
    'o3': 39.34,
    'so2': 17.64,
    'pm2_5': 369.54,
    'pm10': 437.81,
    'nh3': 8.36},
   'dt': 1641099600},
  {'main': {'aqi': 5},
   'components': {'co': 2429.96,
    'no': 10.95,
    'no2': 39.41,
    'o3': 69.38,
    'so2': 18.84,
    'pm2_5': 365.58,
    'pm10': 431.98,
    'nh3': 10.64},
   'dt': 1641103200},
  {'main': {'aqi': 5},
   'components': {'co': 1361.85,
    'no': 1.9,
    'no2': 16.96,
    'o3': 183.11,
    'so2': 26.46,
    'pm2_5': 243.71,
    'pm10': 266.72,
    'nh3': 2.53},
   'dt': 1641106800},
  {'main': {'aqi': 5},
   'components': {'co': 1188.28,
    'no': 1.05,
    'no2': 11.31,
    'o3': 205.99,
    'so2': 23.6,
    'pm2_5': 219.74,
    'pm10': 237.85,
    'nh3': 2.37},
   'dt': 1641110400},
  {'main': {'aqi': 5},
   'components': {'co': 1174.93,
    'no': 0.79,
    'no2': 10.11,
    'o3': 214.58,
    'so2': 22.17,
    'pm2_5': 217.63,
    'pm10': 235.03,
    'nh3': 3.39},
   'dt': 1641114000},
  {'main': {'aqi': 5},
   'components': {'co': 1602.17,
    'no': 2.18,
    'no2': 25.7,
    'o3': 155.93,
    'so2': 20.5,
    'pm2_5': 242,
    'pm10': 276.63,
    'nh3': 9.75},
   'dt': 1641117600},
  {'main': {'aqi': 5},
   'components': {'co': 2243.04,
    'no': 3.55,
    'no2': 52.78,
    'o3': 83.68,
    'so2': 20.27,
    'pm2_5': 279.67,
    'pm10': 338.53,
    'nh3': 17.73},
   'dt': 1641121200},
  {'main': {'aqi': 5},
   'components': {'co': 2803.8,
    'no': 1.84,
    'no2': 86.37,
    'o3': 30.04,
    'so2': 23.84,
    'pm2_5': 303.47,
    'pm10': 378.17,
    'nh3': 26.35},
   'dt': 1641124800},
  {'main': {'aqi': 5},
   'components': {'co': 3124.24,
    'no': 4.86,
    'no2': 104.19,
    'o3': 3.49,
    'so2': 26.94,
    'pm2_5': 322.96,
    'pm10': 411.65,
    'nh3': 33.94},
   'dt': 1641128400},
  {'main': {'aqi': 5},
   'components': {'co': 3204.35,
    'no': 10.06,
    'no2': 95.96,
    'o3': 0.72,
    'so2': 22.65,
    'pm2_5': 343.26,
    'pm10': 444.05,
    'nh3': 27.11},
   'dt': 1641132000},
  {'main': {'aqi': 5},
   'components': {'co': 2990.72,
    'no': 5.2,
    'no2': 83.63,
    'o3': 5.63,
    'so2': 16.93,
    'pm2_5': 349.28,
    'pm10': 443.56,
    'nh3': 15.71},
   'dt': 1641135600},
  {'main': {'aqi': 5},
   'components': {'co': 2429.96,
    'no': 0.02,
    'no2': 57.58,
    'o3': 34.33,
    'so2': 13.47,
    'pm2_5': 320.77,
    'pm10': 391.75,
    'nh3': 9.75},
   'dt': 1641139200},
  {'main': {'aqi': 5},
   'components': {'co': 2456.67,
    'no': 0.16,
    'no2': 54.84,
    'o3': 21.46,
    'so2': 12.4,
    'pm2_5': 325.01,
    'pm10': 403.42,
    'nh3': 8.49},
   'dt': 1641142800},
  {'main': {'aqi': 5},
   'components': {'co': 2349.85,
    'no': 0.64,
    'no2': 52.09,
    'o3': 10.91,
    'so2': 9.89,
    'pm2_5': 313.97,
    'pm10': 389.57,
    'nh3': 7.54},
   'dt': 1641146400},
  {'main': {'aqi': 5},
   'components': {'co': 2136.23,
    'no': 1.16,
    'no2': 46.61,
    'o3': 6.62,
    'so2': 7.75,
    'pm2_5': 293.96,
    'pm10': 354.64,
    'nh3': 6.84},
   'dt': 1641150000},
  {'main': {'aqi': 5},
   'components': {'co': 2056.12,
    'no': 1.93,
    'no2': 42.84,
    'o3': 3.84,
    'so2': 8.58,
    'pm2_5': 288.04,
    'pm10': 342.65,
    'nh3': 7.22},
   'dt': 1641153600},
  {'main': {'aqi': 5},
   'components': {'co': 2002.72,
    'no': 2.46,
    'no2': 39.41,
    'o3': 2.66,
    'so2': 8.82,
    'pm2_5': 287.73,
    'pm10': 340,
    'nh3': 7.28},
   'dt': 1641157200},
  {'main': {'aqi': 5},
   'components': {'co': 1949.31,
    'no': 2.54,
    'no2': 35.99,
    'o3': 2.55,
    'so2': 8.46,
    'pm2_5': 286.43,
    'pm10': 336.35,
    'nh3': 7.16},
   'dt': 1641160800},
  {'main': {'aqi': 5},
   'components': {'co': 1922.61,
    'no': 2.4,
    'no2': 33.59,
    'o3': 2.91,
    'so2': 8.23,
    'pm2_5': 288.78,
    'pm10': 335.89,
    'nh3': 6.4},
   'dt': 1641164400},
  {'main': {'aqi': 5},
   'components': {'co': 1976.01,
    'no': 2.37,
    'no2': 33.59,
    'o3': 3.44,
    'so2': 8.7,
    'pm2_5': 295.2,
    'pm10': 339.5,
    'nh3': 6.02},
   'dt': 1641168000},
  {'main': {'aqi': 5},
   'components': {'co': 2136.23,
    'no': 3.69,
    'no2': 35.99,
    'o3': 3.13,
    'so2': 10.73,
    'pm2_5': 309.88,
    'pm10': 358.36,
    'nh3': 7.09},
   'dt': 1641171600},
  {'main': {'aqi': 5},
   'components': {'co': 2563.48,
    'no': 11.62,
    'no2': 40.44,
    'o3': 0.48,
    'so2': 14.78,
    'pm2_5': 338.63,
    'pm10': 406.66,
    'nh3': 8.87},
   'dt': 1641175200},
  {'main': {'aqi': 5},
   'components': {'co': 2910.61,
    'no': 21.01,
    'no2': 42.16,
    'o3': 2.19,
    'so2': 17.17,
    'pm2_5': 354.56,
    'pm10': 434.68,
    'nh3': 9.37},
   'dt': 1641178800},
  {'main': {'aqi': 5},
   'components': {'co': 2857.21,
    'no': 21.46,
    'no2': 41.81,
    'o3': 15.2,
    'so2': 19.07,
    'pm2_5': 348.89,
    'pm10': 425.28,
    'nh3': 9.63},
   'dt': 1641182400},
  {'main': {'aqi': 5},
   'components': {'co': 2857.21,
    'no': 20.79,
    'no2': 42.84,
    'o3': 32.9,
    'so2': 21.93,
    'pm2_5': 351.85,
    'pm10': 432.9,
    'nh3': 11.78},
   'dt': 1641186000},
  {'main': {'aqi': 5},
   'components': {'co': 2670.29,
    'no': 14.31,
    'no2': 43.87,
    'o3': 65.09,
    'so2': 24.32,
    'pm2_5': 347.85,
    'pm10': 425.18,
    'nh3': 14.44},
   'dt': 1641189600},
  {'main': {'aqi': 5},
   'components': {'co': 1388.55,
    'no': 4.02,
    'no2': 25.02,
    'o3': 141.62,
    'so2': 33.38,
    'pm2_5': 191.29,
    'pm10': 222.05,
    'nh3': 9.37},
   'dt': 1641193200},
  {'main': {'aqi': 5},
   'components': {'co': 1108.17,
    'no': 2.74,
    'no2': 19.19,
    'o3': 154.5,
    'so2': 30.52,
    'pm2_5': 138.94,
    'pm10': 162.25,
    'nh3': 8.99},
   'dt': 1641196800},
  {'main': {'aqi': 5},
   'components': {'co': 947.95,
    'no': 2.04,
    'no2': 16.45,
    'o3': 155.93,
    'so2': 26.7,
    'pm2_5': 119.49,
    'pm10': 139.54,
    'nh3': 9.12},
   'dt': 1641200400},
  {'main': {'aqi': 5},
   'components': {'co': 1174.93,
    'no': 3.02,
    'no2': 25.7,
    'o3': 127.32,
    'so2': 23.6,
    'pm2_5': 129.99,
    'pm10': 161.22,
    'nh3': 12.67},
   'dt': 1641204000},
  {'main': {'aqi': 5},
   'components': {'co': 1789.09,
    'no': 4.47,
    'no2': 48.67,
    'o3': 80.11,
    'so2': 23.84,
    'pm2_5': 160.64,
    'pm10': 211.43,
    'nh3': 18.49},
   'dt': 1641207600},
  {'main': {'aqi': 5},
   'components': {'co': 2429.96,
    'no': 2.54,
    'no2': 80.88,
    'o3': 31.47,
    'so2': 25.51,
    'pm2_5': 193.28,
    'pm10': 257.57,
    'nh3': 24.07},
   'dt': 1641211200},
  {'main': {'aqi': 5},
   'components': {'co': 2937.32,
    'no': 3.86,
    'no2': 97.33,
    'o3': 4.78,
    'so2': 26.23,
    'pm2_5': 226.91,
    'pm10': 304.24,
    'nh3': 25.33},
   'dt': 1641214800},
  {'main': {'aqi': 5},
   'components': {'co': 3150.94,
    'no': 8.16,
    'no2': 90.48,
    'o3': 1.35,
    'so2': 25.51,
    'pm2_5': 258.82,
    'pm10': 353.85,
    'nh3': 21.53},
   'dt': 1641218400},
  {'main': {'aqi': 5},
   'components': {'co': 3204.35,
    'no': 9.28,
    'no2': 82.25,
    'o3': 0.95,
    'so2': 23.37,
    'pm2_5': 287.6,
    'pm10': 393.81,
    'nh3': 16.21},
   'dt': 1641222000},
  {'main': {'aqi': 5},
   'components': {'co': 3417.97,
    'no': 13.97,
    'no2': 74.71,
    'o3': 0.32,
    'so2': 21.93,
    'pm2_5': 326.79,
    'pm10': 445.11,
    'nh3': 13.3},
   'dt': 1641225600},
  {'main': {'aqi': 5},
   'components': {'co': 3791.81,
    'no': 24.14,
    'no2': 66.49,
    'o3': 0.02,
    'so2': 21.22,
    'pm2_5': 369.5,
    'pm10': 503.65,
    'nh3': 12.79},
   'dt': 1641229200},
  {'main': {'aqi': 5},
   'components': {'co': 3738.4,
    'no': 27.94,
    'no2': 59.63,
    'o3': 0.01,
    'so2': 17.17,
    'pm2_5': 376.67,
    'pm10': 505.22,
    'nh3': 11.02},
   'dt': 1641232800},
  {'main': {'aqi': 5},
   'components': {'co': 3364.56,
    'no': 25.7,
    'no2': 52.09,
    'o3': 0.01,
    'so2': 12.52,
    'pm2_5': 358.17,
    'pm10': 458.79,
    'nh3': 8.61},
   'dt': 1641236400},
  {'main': {'aqi': 5},
   'components': {'co': 3044.13,
    'no': 21.9,
    'no2': 44.55,
    'o3': 0.01,
    'so2': 11.68,
    'pm2_5': 348.15,
    'pm10': 429.2,
    'nh3': 8.61},
   'dt': 1641240000},
  {'main': {'aqi': 5},
   'components': {'co': 2830.51,
    'no': 19.22,
    'no2': 38.73,
    'o3': 0.02,
    'so2': 11.92,
    'pm2_5': 345.38,
    'pm10': 417.12,
    'nh3': 9.37},
   'dt': 1641243600},
  {'main': {'aqi': 5},
   'components': {'co': 2643.59,
    'no': 17.21,
    'no2': 33.93,
    'o3': 0.02,
    'so2': 12.52,
    'pm2_5': 340.98,
    'pm10': 408.99,
    'nh3': 10.64},
   'dt': 1641247200},
  {'main': {'aqi': 5},
   'components': {'co': 2590.18,
    'no': 17.66,
    'no2': 30.85,
    'o3': 0.02,
    'so2': 13.59,
    'pm2_5': 341.05,
    'pm10': 408.12,
    'nh3': 11.65},
   'dt': 1641250800},
  {'main': {'aqi': 5},
   'components': {'co': 2670.29,
    'no': 21.9,
    'no2': 28.79,
    'o3': 0.01,
    'so2': 16.21,
    'pm2_5': 350.6,
    'pm10': 423.27,
    'nh3': 13.3},
   'dt': 1641254400},
  {'main': {'aqi': 5},
   'components': {'co': 3017.43,
    'no': 33.08,
    'no2': 27.08,
    'o3': 0,
    'so2': 20.27,
    'pm2_5': 377.38,
    'pm10': 467.77,
    'nh3': 15.71},
   'dt': 1641258000},
  {'main': {'aqi': 5},
   'components': {'co': 4005.43,
    'no': 60.8,
    'no2': 26.39,
    'o3': 0,
    'so2': 23.84,
    'pm2_5': 438.37,
    'pm10': 567.02,
    'nh3': 14.57},
   'dt': 1641261600},
  {'main': {'aqi': 5},
   'components': {'co': 5126.95,
    'no': 95.67,
    'no2': 29.13,
    'o3': 0.37,
    'so2': 24.32,
    'pm2_5': 496.59,
    'pm10': 647.69,
    'nh3': 11.4},
   'dt': 1641265200},
  {'main': {'aqi': 5},
   'components': {'co': 4432.68,
    'no': 62.58,
    'no2': 51.41,
    'o3': 7.06,
    'so2': 27.66,
    'pm2_5': 432.57,
    'pm10': 535.45,
    'nh3': 11.78},
   'dt': 1641268800},
  {'main': {'aqi': 5},
   'components': {'co': 4753.11,
    'no': 50.07,
    'no2': 71.97,
    'o3': 24.32,
    'so2': 30.99,
    'pm2_5': 462.11,
    'pm10': 572.65,
    'nh3': 14.57},
   'dt': 1641272400},
  {'main': {'aqi': 5},
   'components': {'co': 4432.68,
    'no': 23.92,
    'no2': 82.25,
    'o3': 75.82,
    'so2': 32.9,
    'pm2_5': 465.64,
    'pm10': 570.92,
    'nh3': 16.47},
   'dt': 1641276000},
  {'main': {'aqi': 5},
   'components': {'co': 1642.23,
    'no': 4.69,
    'no2': 34.96,
    'o3': 150.2,
    'so2': 43.39,
    'pm2_5': 202.73,
    'pm10': 239.25,
    'nh3': 7.28},
   'dt': 1641279600},
  {'main': {'aqi': 5},
   'components': {'co': 1348.5,
    'no': 2.99,
    'no2': 30.16,
    'o3': 160.22,
    'so2': 44.35,
    'pm2_5': 181.53,
    'pm10': 212.74,
    'nh3': 8.11},
   'dt': 1641283200},
  {'main': {'aqi': 5},
   'components': {'co': 1281.74,
    'no': 1.9,
    'no2': 30.16,
    'o3': 161.65,
    'so2': 43.87,
    'pm2_5': 174.96,
    'pm10': 207.29,
    'nh3': 9.88},
   'dt': 1641286800},
  {'main': {'aqi': 5},
   'components': {'co': 1695.63,
    'no': 1.65,
    'no2': 46.61,
    'o3': 110.15,
    'so2': 35.76,
    'pm2_5': 193.17,
    'pm10': 248.7,
    'nh3': 16.47},
   'dt': 1641290400},
  {'main': {'aqi': 5},
   'components': {'co': 2403.26,
    'no': 2.18,
    'no2': 74.71,
    'o3': 42.56,
    'so2': 30.99,
    'pm2_5': 234.29,
    'pm10': 323.7,
    'nh3': 24.57},
   'dt': 1641294000},
  {'main': {'aqi': 5},
   'components': {'co': 3044.13,
    'no': 12.85,
    'no2': 91.85,
    'o3': 3.22,
    'so2': 32.42,
    'pm2_5': 275.84,
    'pm10': 394.05,
    'nh3': 32.42},
   'dt': 1641297600},
  {'main': {'aqi': 5},
   'components': {'co': 3311.16,
    'no': 30.85,
    'no2': 83.63,
    'o3': 0.01,
    'so2': 36.24,
    'pm2_5': 315.07,
    'pm10': 458.36,
    'nh3': 43.06},
   'dt': 1641301200},
  {'main': {'aqi': 5},
   'components': {'co': 3471.37,
    'no': 37.1,
    'no2': 77.46,
    'o3': 0,
    'so2': 40.53,
    'pm2_5': 358.04,
    'pm10': 531.05,
    'nh3': 51.68},
   'dt': 1641304800},
  {'main': {'aqi': 5},
   'components': {'co': 3738.4,
    'no': 39.34,
    'no2': 71.29,
    'o3': 0,
    'so2': 42.92,
    'pm2_5': 397.01,
    'pm10': 599.73,
    'nh3': 54.21},
   'dt': 1641308400},
  {'main': {'aqi': 5},
   'components': {'co': 3898.62,
    'no': 38.44,
    'no2': 63.75,
    'o3': 0,
    'so2': 42.44,
    'pm2_5': 428.83,
    'pm10': 655.63,
    'nh3': 52.18},
   'dt': 1641312000},
  {'main': {'aqi': 5},
   'components': {'co': 3898.62,
    'no': 37.1,
    'no2': 55.52,
    'o3': 0,
    'so2': 39.1,
    'pm2_5': 436.16,
    'pm10': 668.34,
    'nh3': 48.13},
   'dt': 1641315600},
  {'main': {'aqi': 5},
   'components': {'co': 3524.78,
    'no': 32.63,
    'no2': 49.35,
    'o3': 0,
    'so2': 31.47,
    'pm2_5': 409.62,
    'pm10': 613.54,
    'nh3': 40.53},
   'dt': 1641319200},
  {'main': {'aqi': 5},
   'components': {'co': 3070.83,
    'no': 26.15,
    'no2': 46.61,
    'o3': 0.01,
    'so2': 23.37,
    'pm2_5': 378.07,
    'pm10': 533.27,
    'nh3': 32.17},
   'dt': 1641322800},
  {'main': {'aqi': 5},

In [576]:
date=[]
for i in data1["list"]:   
    date.append(i["dt"])

In [577]:
date=pd.DataFrame(date)

In [578]:
date

                0
0      1640977200
1      1640980800
2      1640984400
3      1640988000
4      1640991600
...           ...
34769  1768564800
34770  1768568400
34771  1768572000
34772  1768575600
34773  1768579200

[34774 rows x 1 columns]

In [579]:
date.columns=["Date"]

In [580]:
date

             Date
0      1640977200
1      1640980800
2      1640984400
3      1640988000
4      1640991600
...           ...
34769  1768564800
34770  1768568400
34771  1768572000
34772  1768575600
34773  1768579200

[34774 rows x 1 columns]

In [581]:
components=[]
for i in data1["list"]:   
    components.append(i["components"])

In [582]:
components=pd.DataFrame(components)

In [583]:
components

            co    no    no2      o3    so2   pm2_5    pm10    nh3
0      2269.74  1.09  64.43    7.06  10.01  230.56  292.91   5.64
1      1976.01  0.69  52.78    7.51   7.63  221.76  272.03   5.07
2      1842.50  0.89  45.24    5.99   7.09  221.30  266.47   5.26
3      1762.39  1.36  40.10    4.07   6.79  224.94  266.86   5.64
4      1708.98  1.63  37.01    3.58   6.79  230.35  269.00   5.38
...        ...   ...    ...     ...    ...     ...     ...    ...
34769   877.89  0.46  28.00  136.00  10.27  156.11  194.25  11.83
34770  1042.84  0.01  37.18  112.41  12.13  172.89  213.30  15.09
34771  1213.52  0.00  41.85   94.17  13.73  195.48  238.44  17.18
34772  1359.43  0.00  42.98   77.67  14.02  217.60  261.84  17.14
34773  1430.73  0.00  39.86   56.82   8.74  230.18  271.93   8.39

[34774 rows x 8 columns]

In [584]:
df=pd.concat([date,components],axis=1)

In [585]:
df

             Date       co    no    no2      o3    so2   pm2_5    pm10    nh3
0      1640977200  2269.74  1.09  64.43    7.06  10.01  230.56  292.91   5.64
1      1640980800  1976.01  0.69  52.78    7.51   7.63  221.76  272.03   5.07
2      1640984400  1842.50  0.89  45.24    5.99   7.09  221.30  266.47   5.26
3      1640988000  1762.39  1.36  40.10    4.07   6.79  224.94  266.86   5.64
4      1640991600  1708.98  1.63  37.01    3.58   6.79  230.35  269.00   5.38
...           ...      ...   ...    ...     ...    ...     ...     ...    ...
34769  1768564800   877.89  0.46  28.00  136.00  10.27  156.11  194.25  11.83
34770  1768568400  1042.84  0.01  37.18  112.41  12.13  172.89  213.30  15.09
34771  1768572000  1213.52  0.00  41.85   94.17  13.73  195.48  238.44  17.18
34772  1768575600  1359.43  0.00  42.98   77.67  14.02  217.60  261.84  17.14
34773  1768579200  1430.73  0.00  39.86   56.82   8.74  230.18  271.93   8.39

[34774 rows x 9 columns]

In [586]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34774 entries, 0 to 34773
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    34774 non-null  int64
 1   co      34774 non-null  float64
 2   no      34774 non-null  float64
 3   no2     34774 non-null  float64
 4   o3      34774 non-null  float64
 5   so2     34774 non-null  float64
 6   pm2_5   34774 non-null  float64
 7   pm10    34774 non-null  float64
 8   nh3     34774 non-null  float64
dtypes: float64(8), int64(1)
memory usage: 2.4 MB

In [587]:
df["Date"]=df["Date"].apply(lambda x : datetime.fromtimestamp(x))

In [588]:
df.columns=["Date","CO","NO","No2","O3","So2","PM2.5","PM10","NH3"]

In [590]:
df["Date"]=df["Date"].dt.date

In [591]:
df

             Date       CO    NO    No2      O3    So2   PM2.5    PM10    NH3
0      2022-01-01  2269.74  1.09  64.43    7.06  10.01  230.56  292.91   5.64
1      2022-01-01  1976.01  0.69  52.78    7.51   7.63  221.76  272.03   5.07
2      2022-01-01  1842.50  0.89  45.24    5.99   7.09  221.30  266.47   5.26
3      2022-01-01  1762.39  1.36  40.10    4.07   6.79  224.94  266.86   5.64
4      2022-01-01  1708.98  1.63  37.01    3.58   6.79  230.35  269.00   5.38
...           ...      ...   ...    ...     ...    ...     ...     ...    ...
34769  2026-01-16   877.89  0.46  28.00  136.00  10.27  156.11  194.25  11.83
34770  2026-01-16  1042.84  0.01  37.18  112.41  12.13  172.89  213.30  15.09
34771  2026-01-16  1213.52  0.00  41.85   94.17  13.73  195.48  238.44  17.18
34772  2026-01-16  1359.43  0.00  42.98   77.67  14.02  217.60  261.84  17.14
34773  2026-01-16  1430.73  0.00  39.86   56.82   8.74  230.18  271.93   8.39

[34774 rows x 9 columns]

In [593]:
df.groupby("Date")[["CO","NO","No2","O3","So2","PM2.5","PM10","NH3"]].mean()

,CO,NO,No2,O3,So2,PM2.5,PM10,NH3
Date,,,,,,,,
2022-01-01,2372.661667,6.114167,52.553750,42.277083,16.318333,278.941250,339.754583,11.345417
2022-01-02,2301.455000,3.713750,47.581667,49.602083,15.218333,323.369583,380.540000,10.209583
2022-01-03,2379.894583,8.830000,48.580833,34.974583,19.063333,273.821667,341.334583,11.874583
2022-01-04,3173.749167,28.809583,51.109167,30.652917,29.245833,348.510000,460.807083,22.300000
2022-01-05,3342.865833,31.397500,62.833750,16.685833,58.303333,433.102500,502.718750,9.956250
...,...,...,...,...,...,...,...,...
2026-01-12,1023.270000,0.660833,17.792083,83.259583,5.187500,178.972083,201.211250,4.645000
2026-01-13,1209.258333,1.156250,19.565417,61.472500,5.565417,223.143750,241.928333,5.233750
2026-01-14,1213.689583,0.347500,21.538333,69.656250,6.960833,243.778333,277.277917,7.676250
2026-01-15,947.652500,1.000833,20.145833,69.644167,5.812500,173.542500,207.150417,6.149583
2026-01-16,972.790909,1.357273,22.112727,88.278182,8.221818,165.892273,207.081818,8.947727

In [594]:
df["CO"]=df["CO"]/1000

In [595]:
aqi_data={
    "ihi":[50,100,200,300,400,500],
    "ilo":[0,51,101,201,301,401],
    "bphi2.5":[30,60,90,120,250,550],
    "bplo2.5":[0,31,61,91,121,251],
    "bphipm10":[50,100,250,350,430,500],
    "bplopm10":[0,51,101,251,351,431],
    "bphico":[1,2,10,17,34,50],
    "bploco":[0,1.1,2.1,10.1,17.1,50.1],
    "bphio3":[50,100,168,208,748,1000],
    "bploo3":[0,51,101,169,209,749],
    "bphino2":[40,80,180,280,400,600],
    "bplono2":[0,41,81,181,281,401],
    "bphiso2":[40,80,380,800,1600,2000],
    "bploso2":[0,41,81,381,801,1601],
    "bphinh3":[200,400,800,1200,1800,2000],
    "bplonh3":[0,201,401,801,1201,1801]
}

In [596]:
aqi_data=pd.DataFrame(aqi_data)
aqi_data

,ihi,ilo,bphi2.5,bplo2.5,bphipm10,bplopm10,bphico,bploco,bphio3,bploo3,bphino2,bplono2,bphiso2,bploso2,bphinh3,bplonh3
0,50,0,30,0,50,0,1,0.0,50,0,40,0,40,0,200,0
1,100,51,60,31,100,51,2,1.1,100,51,80,41,80,41,400,201
2,200,101,90,61,250,101,10,2.1,168,101,180,81,380,81,800,401
3,300,201,120,91,350,251,17,10.1,208,169,280,181,800,381,1200,801
4,400,301,250,121,430,351,34,17.1,748,209,400,281,1600,801,1800,1201
5,500,401,550,251,500,431,50,50.1,1000,749,600,401,2000,1601,2000,1801

In [597]:
def aqi25(a,aqi_data):
    row=aqi_data[(aqi_data["bplo2.5"] <= a) & (aqi_data["bphi2.5"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphi2_5=aqi_data["bphi2.5"].iloc[0]
    bplo2_5=aqi_data["bplo2.5"].iloc[0]
    aqi2_5=((ihi - ilo) / (bphi2_5 - bplo2_5)) * (a - bplo2_5) + ilo
    return aqi2_5

In [598]:
def aqi10(a,aqi_data):
    row=aqi_data[(aqi_data["bplopm10"] <= a) & (aqi_data["bphipm10"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphi10=aqi_data["bphipm10"].iloc[0]
    bplo10=aqi_data["bplopm10"].iloc[0]
    aqi10=((ihi - ilo) / (bphi10 - bplo10)) * (a - bplo10) + ilo
    return aqi10

In [599]:
def aqio3(a,aqi_data):
    row=aqi_data[(aqi_data["bploo3"] <= a) & (aqi_data["bphio3"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphio3=aqi_data["bphio3"].iloc[0]
    bploo3=aqi_data["bploo3"].iloc[0]
    aqio3=((ihi - ilo) / (bphio3 - bploo3)) * (a - bploo3) + ilo
    return aqio3

In [600]:
def aqico(a,aqi_data):
    row=aqi_data[(aqi_data["bploco"] <= a) & (aqi_data["bphico"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphico=aqi_data["bphico"].iloc[0]
    bploco=aqi_data["bploco"].iloc[0]
    aqico=((ihi - ilo) / (bphico - bploco)) * (a - bploco) + ilo
    return aqico

In [601]:
def aqino2(a,aqi_data):
    row=aqi_data[(aqi_data["bplono2"] <= a) & (aqi_data["bphino2"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphino2=aqi_data["bphino2"].iloc[0]
    bplono2=aqi_data["bplono2"].iloc[0]
    aqino2=((ihi - ilo) / (bphino2 - bplono2)) * (a - bplono2) + ilo
    return aqino2

In [602]:
def aqiso2(a,aqi_data):
    row=aqi_data[(aqi_data["bploso2"] <= a) & (aqi_data["bphiso2"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphiso2=aqi_data["bphiso2"].iloc[0]
    bploso2=aqi_data["bploso2"].iloc[0]
    aqiso2=((ihi - ilo) / (bphiso2 - bploso2)) * (a - bploso2) + ilo
    return aqiso2

In [603]:
def aqinh3(a,aqi_data):
    row=aqi_data[(aqi_data["bplonh3"] <= a) & (aqi_data["bphinh3"] >= a)]
    ihi=aqi_data["ihi"].iloc[0]
    ilo=aqi_data["ilo"].iloc[0]
    bphinh3=aqi_data["bphinh3"].iloc[0]
    bplonh3=aqi_data["bplonh3"].iloc[0]
    aqinh3=((ihi - ilo) / (bphinh3 - bplonh3)) * (a - bplonh3) + ilo
    return aqinh3

In [604]:
df

             Date       CO    NO    No2      O3    So2   PM2.5    PM10    NH3
0      2022-01-01  2.26974  1.09  64.43    7.06  10.01  230.56  292.91   5.64
1      2022-01-01  1.97601  0.69  52.78    7.51   7.63  221.76  272.03   5.07
2      2022-01-01  1.84250  0.89  45.24    5.99   7.09  221.30  266.47   5.26
3      2022-01-01  1.76239  1.36  40.10    4.07   6.79  224.94  266.86   5.64
4      2022-01-01  1.70898  1.63  37.01    3.58   6.79  230.35  269.00   5.38
...           ...      ...   ...    ...     ...    ...     ...     ...    ...
34769  2026-01-16  0.87789  0.46  28.00  136.00  10.27  156.11  194.25  11.83
34770  2026-01-16  1.04284  0.01  37.18  112.41  12.13  172.89  213.30  15.09
34771  2026-01-16  1.21352  0.00  41.85   94.17  13.73  195.48  238.44  17.18
34772  2026-01-16  1.35943  0.00  42.98   77.67  14.02  217.60  261.84  17.14
34773  2026-01-16  1.43073  0.00  39.86   56.82   8.74  230.18  271.93   8.39

[34774 rows x 9 columns]

In [605]:
df["AQI2.5"] = df["PM2.5"].apply(lambda x: aqi25(x, aqi_data))

In [606]:
df["AQI10"] = df["PM10"].apply(lambda x: aqi10(x, aqi_data))

In [607]:
df["AQICO"] = df["CO"].apply(lambda x: aqico(x, aqi_data))

In [608]:
df["AQINO2"] = df["No2"].apply(lambda x: aqino2(x, aqi_data))

In [609]:
df["AQIO3"] = df["O3"].apply(lambda x: aqio3(x, aqi_data))

In [610]:
df["AQISO2"] = df["So2"].apply(lambda x: aqiso2(x, aqi_data))

In [611]:
df["AQINH3"] = df["NH3"].apply(lambda x: aqinh3(x, aqi_data))

In [612]:
df

,Date,CO,NO,No2,O3,So2,PM2.5,PM10,NH3,AQI2.5,AQI10,AQICO,AQINO2,AQIO3,AQISO2,AQINH3
0,2022-01-01,2.26974,1.09,64.43,7.06,10.01,230.56,292.91,5.64,384.266667,292.91,113.4870,80.5375,7.06,12.5125,1.4100
1,2022-01-01,1.97601,0.69,52.78,7.51,7.63,221.76,272.03,5.07,369.600000,272.03,98.8005,65.9750,7.51,9.5375,1.2675
2,2022-01-01,1.84250,0.89,45.24,5.99,7.09,221.30,266.47,5.26,368.833333,266.47,92.1250,56.5500,5.99,8.8625,1.3150
3,2022-01-01,1.76239,1.36,40.10,4.07,6.79,224.94,266.86,5.64,374.900000,266.86,88.1195,50.1250,4.07,8.4875,1.4100
4,2022-01-01,1.70898,1.63,37.01,3.58,6.79,230.35,269.00,5.38,383.916667,269.00,85.4490,46.2625,3.58,8.4875,1.3450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34769,2026-01-16,0.87789,0.46,28.00,136.00,10.27,156.11,194.25,11.83,260.183333,194.25,43.8945,35.0000,136.00,12.8375,2.9575
34770,2026-01-16,1.04284,0.01,37.18,112.41,12.13,172.89,213.30,15.09,288.150000,213.30,52.1420,46.4750,112.41,15.1625,3.7725
34771,2026-01-16,1.21352,0.00,41.85,94.17,13.73,195.48,238.44,17.18,325.800000,238.44,60.6760,52.3125,94.17,17.1625,4.2950
34772,2026-01-16,1.35943,0.00,42.98,77.67,14.02,217.60,261.84,17.14,362.666667,261.84,67.9715,53.7250,77.67,17.5250,4.2850
34773,2026-01-16,1.43073,0.00,39.86,56.82,8.74,230.18,271.93,8.39,383.633333,271.93,71.5365,49.8250,56.82,10.9250,2.0975

In [613]:
aqi_df=df[["Date","CO","No2","O3","So2","PM2.5","PM10","NH3","AQI2.5"]]

In [614]:
aqi_df.columns=["date","co","no2","o3","so2","pm2.5","pm10","nh3","aqi"]

In [615]:
aqi_df

,date,co,no2,o3,so2,pm2.5,pm10,nh3,aqi
0,2022-01-01,2.26974,64.43,7.06,10.01,230.56,292.91,5.64,384.266667
1,2022-01-01,1.97601,52.78,7.51,7.63,221.76,272.03,5.07,369.600000
2,2022-01-01,1.84250,45.24,5.99,7.09,221.30,266.47,5.26,368.833333
3,2022-01-01,1.76239,40.10,4.07,6.79,224.94,266.86,5.64,374.900000
4,2022-01-01,1.70898,37.01,3.58,6.79,230.35,269.00,5.38,383.916667
...,...,...,...,...,...,...,...,...,...
34769,2026-01-16,0.87789,28.00,136.00,10.27,156.11,194.25,11.83,260.183333
34770,2026-01-16,1.04284,37.18,112.41,12.13,172.89,213.30,15.09,288.150000
34771,2026-01-16,1.21352,41.85,94.17,13.73,195.48,238.44,17.18,325.800000
34772,2026-01-16,1.35943,42.98,77.67,14.02,217.60,261.84,17.14,362.666667
34773,2026-01-16,1.43073,39.86,56.82,8.74,230.18,271.93,8.39,383.633333

In [616]:
aqi_df["co"]=aqi_df["co"]*1000

C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\2614576533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aqi_df["co"]=aqi_df["co"]*1000

In [617]:
del df

In [618]:
df=aqi_df

In [619]:
df.copy()

,date,co,no2,o3,so2,pm2.5,pm10,nh3,aqi
0,2022-01-01,2269.74,64.43,7.06,10.01,230.56,292.91,5.64,384.266667
1,2022-01-01,1976.01,52.78,7.51,7.63,221.76,272.03,5.07,369.600000
2,2022-01-01,1842.50,45.24,5.99,7.09,221.30,266.47,5.26,368.833333
3,2022-01-01,1762.39,40.10,4.07,6.79,224.94,266.86,5.64,374.900000
4,2022-01-01,1708.98,37.01,3.58,6.79,230.35,269.00,5.38,383.916667
...,...,...,...,...,...,...,...,...,...
34769,2026-01-16,877.89,28.00,136.00,10.27,156.11,194.25,11.83,260.183333
34770,2026-01-16,1042.84,37.18,112.41,12.13,172.89,213.30,15.09,288.150000
34771,2026-01-16,1213.52,41.85,94.17,13.73,195.48,238.44,17.18,325.800000
34772,2026-01-16,1359.43,42.98,77.67,14.02,217.60,261.84,17.14,362.666667
34773,2026-01-16,1430.73,39.86,56.82,8.74,230.18,271.93,8.39,383.633333

In [620]:
for lag in range(1,25):
    df[f"pm2.5lag{lag}"]=df["pm2.5"].shift(lag)
    df[f"pm10lagP{lag}"]=df["pm10"].shift(lag)
df["pm2.5roll7"]=df["pm2.5"].rolling(7).mean()
df["pm2.5roll14"]=df["pm2.5"].rolling(14).mean()
df["pm2.5roll21"]=df["pm2.5"].rolling(21).mean()
df["pm10roll7"]=df["pm10"].rolling(7).mean()
df["pm10roll14"]=df["pm10"].rolling(14).mean()
df["pm10roll21"]=df["pm10"].rolling(21).mean()

C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\3236190133.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"pm2.5lag{lag}"]=df["pm2.5"].shift(lag)
C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\3236190133.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"pm10lagP{lag}"]=df["pm10"].shift(lag)
C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\3236190133.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"pm2.5lag{lag}"]=df["pm2.5"].shift(lag)
C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\3236190133.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"pm10lagP{lag}"]=df["pm10"].shift(lag)
C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\3236190133.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"pm2.5lag{lag}"]=df["pm2.5"].shift(lag)
C:\Users\sahil\AppData\Local\Temp\ipykernel_18404\3236190133.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f"pm10lagP{lag}"]=df["pm10"].shift(lag)

In [621]:
df=df.dropna().reset_index(drop=True)

In [622]:
X=df.drop(["date","co","no2","o3","so2","pm2.5","pm10","nh3","aqi"],axis=1)
y_25=df["pm2.5"]
y_10=df["pm10"]

In [623]:
X

,pm2.5lag1,pm10lagP1,pm2.5lag2,pm10lagP2,pm2.5lag3,pm10lagP3,pm2.5lag4,pm10lagP4,pm2.5lag5,pm10lagP5,...,pm2.5lag23,pm10lagP23,pm2.5lag24,pm10lagP24,pm2.5roll7,pm2.5roll14,pm2.5roll21,pm10roll7,pm10roll14,pm10roll21
0,364.37,454.05,369.74,465.01,359.00,451.49,366.60,474.95,349.62,457.05,...,221.76,272.03,230.56,292.91,353.460000,305.228571,292.394286,447.157143,373.195714,355.724762
1,344.25,414.38,364.37,454.05,369.74,465.01,359.00,451.49,366.60,474.95,...,221.30,266.47,221.76,272.03,355.130000,307.730714,297.250476,443.430000,374.978571,361.347619
2,332.33,387.08,344.25,414.38,364.37,454.05,369.74,465.01,359.00,451.49,...,224.94,266.86,221.30,266.47,352.440000,311.847143,301.746667,431.815714,380.611429,366.278571
3,330.79,375.75,332.33,387.08,344.25,414.38,364.37,454.05,369.74,465.01,...,230.35,269.00,224.94,266.86,348.175714,318.858571,305.953333,417.497143,388.992857,370.390000
4,336.75,374.72,330.79,375.75,332.33,387.08,344.25,414.38,364.37,454.05,...,236.37,272.20,230.35,269.00,346.332857,328.390000,309.453810,407.467143,399.796429,372.890000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34745,142.29,178.96,126.19,161.58,116.14,150.91,115.75,152.24,126.84,167.17,...,137.61,168.71,127.50,157.46,139.101429,154.107857,159.400000,177.061429,196.120714,199.687619
34746,156.11,194.25,142.29,178.96,126.19,161.58,116.14,150.91,115.75,152.24,...,150.24,183.39,137.61,168.71,136.601429,154.620714,159.691905,174.058571,196.530000,200.189048
34747,172.89,213.30,156.11,194.25,142.29,178.96,126.19,161.58,116.14,150.91,...,161.10,196.34,150.24,183.39,146.407143,156.865000,160.786667,184.240000,198.647857,201.582381
34748,195.48,238.44,172.89,213.30,156.11,194.25,142.29,178.96,126.19,161.58,...,166.76,202.77,161.10,196.34,160.957143,160.743571,162.830952,199.897143,202.302857,203.993810
34749,217.60,261.84,195.48,238.44,172.89,213.30,156.11,194.25,142.29,178.96,...,172.49,209.18,166.76,202.77,177.248571,165.320714,165.633810,217.185714,206.336429,207.083810

In [624]:
y_25

0        344.25
1        332.33
2        330.79
3        336.75
4        346.10
          ...
34745    156.11
34746    172.89
34747    195.48
34748    217.60
34749    230.18
Name: pm2.5, Length: 34750, dtype: float64

In [625]:
y_10

0        414.38
1        387.08
2        375.75
3        374.72
4        381.28
          ...
34745    194.25
34746    213.30
34747    238.44
34748    261.84
34749    271.93
Name: pm10, Length: 34750, dtype: float64

In [626]:
# spiliting for training and testing of data
X_train=X.iloc[:round(len(X)*0.8)]
X_test=X.iloc[round(len(X)*0.8):]

In [627]:
y25_train=y_25.iloc[:round(len(X)*0.8)]
y25_test=y_25.iloc[round(len(X)*0.8):]

In [628]:
y10_train=y_10.iloc[:round(len(X)*0.8)]
y10_test=y_10.iloc[round(len(X)*0.8):]

In [629]:
from sklearn.ensemble import RandomForestRegressor
rf_25 = RandomForestRegressor(
    n_estimators=300,
    max_depth=12,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)
rf_25.fit(X_train,y25_train)

RandomForestRegressor(max_depth=12, min_samples_leaf=5, n_estimators=300,
                      n_jobs=-1, random_state=42)

In [630]:
from sklearn.ensemble import RandomForestRegressor
rf_10 = RandomForestRegressor(
    n_estimators=300,
    max_depth=12,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)
rf_10.fit(X_train,y10_train)

RandomForestRegressor(max_depth=12, min_samples_leaf=5, n_estimators=300,
                      n_jobs=-1, random_state=42)

In [631]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
y25_pred=rf_25.predict(X_test)
y10_pred=rf_10.predict(X_test)

In [632]:
k = X.shape[1]
n = len(y25_test)
mse25=mean_squared_error(y25_test,y25_pred)
mae25=mean_absolute_error(y25_test,y25_pred)
r2_25=r2_score(y25_test,y25_pred)
adj_r2_25=1-(((1-r2_25)*(n-1))/(n-k-1))
mse10=mean_squared_error(y10_test,y10_pred)
mae10=mean_absolute_error(y10_test,y10_pred)
r2_10=r2_score(y10_test,y10_pred)
adj_r2_10=1-(((1-r2_10)*(n-1))/(n-k-1))

In [633]:
print(f"mse25={mse25},mae25={mae25},r2_25={r2_25},adj_r225={adj_r2_25}")
print(f"mse10={mse10},mae10={mae10},r2_10={r2_10},adj_r210={adj_r2_10}")

mse25=55.32763326335326,mae25=2.9498334857399664,r2_25=0.9852320445818605,adj_r225=0.9851163854676358
mse10=2121.560191107704,mae10=11.673031542566099,r2_10=0.5908180787112332,adj_r210=0.5876134632290586

In [634]:
df1=df.drop(["date","co","no2","o3","so2","pm2.5","pm10","nh3","aqi"],axis=1)

In [635]:
df1=df1.dropna().reset_index(drop=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34750 entries, 0 to 34749
Data columns (total 54 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pm2.5lag1    34750 non-null  float64
 1   pm10lagP1    34750 non-null  float64
 2   pm2.5lag2    34750 non-null  float64
 3   pm10lagP2    34750 non-null  float64
 4   pm2.5lag3    34750 non-null  float64
 5   pm10lagP3    34750 non-null  float64
 6   pm2.5lag4    34750 non-null  float64
 7   pm10lagP4    34750 non-null  float64
 8   pm2.5lag5    34750 non-null  float64
 9   pm10lagP5    34750 non-null  float64
 10  pm2.5lag6    34750 non-null  float64
 11  pm10lagP6    34750 non-null  float64
 12  pm2.5lag7    34750 non-null  float64
 13  pm10lagP7    34750 non-null  float64
 14  pm2.5lag8    34750 non-null  float64
 15  pm10lagP8    34750 non-null  float64
 16  pm2.5lag9    34750 non-null  float64
 17  pm10lagP9    34750 non-null  float64
 18  pm2.5lag10   34750 non-null  float64
 19  pm10lagP10   34750 non-null  float64
 20  pm2.5lag11   34750 non-null  float64
 21  pm10lagP11   34750 non-null  float64
 22  pm2.5lag12   34750 non-null  float64
 23  pm10lagP12   34750 non-null  float64
 24  pm2.5lag13   34750 non-null  float64
 25  pm10lagP13   34750 non-null  float64
 26  pm2.5lag14   34750 non-null  float64
 27  pm10lagP14   34750 non-null  float64
 28  pm2.5lag15   34750 non-null  float64
 29  pm10lagP15   34750 non-null  float64
 30  pm2.5lag16   34750 non-null  float64
 31  pm10lagP16   34750 non-null  float64
 32  pm2.5lag17   34750 non-null  float64
 33  pm10lagP17   34750 non-null  float64
 34  pm2.5lag18   34750 non-null  float64
 35  pm10lagP18   34750 non-null  float64
 36  pm2.5lag19   34750 non-null  float64
 37  pm10lagP19   34750 non-null  float64
 38  pm2.5lag20   34750 non-null  float64
 39  pm10lagP20   34750 non-null  float64
 40  pm2.5lag21   34750 non-null  float64
 41  pm10lagP21   34750 non-null  float64
 42  pm2.5lag22   34750 non-null  float64
 43  pm10lagP22   34750 non-null  float64
 44  pm2.5lag23   34750 non-null  float64
 45  pm10lagP23   34750 non-null  float64
 46  pm2.5lag24   34750 non-null  float64
 47  pm10lagP24   34750 non-null  float64
 48  pm2.5roll7   34750 non-null  float64
 49  pm2.5roll14  34750 non-null  float64
 50  pm2.5roll21  34750 non-null  float64
 51  pm10roll7    34750 non-null  float64
 52  pm10roll14   34750 non-null  float64
 53  pm10roll21   34750 non-null  float64
dtypes: float64(54)
memory usage: 14.3 MB

In [636]:
last_known=df1.iloc[-1:]

In [637]:
future_pm25 = []
future_pm10 = []
last_known = X.iloc[-1:].copy()   
for _ in range(10):
    next_pm25 = rf_25.predict(last_known)[0]
    next_pm10 = rf_10.predict(last_known)[0]
    future_pm25.append(next_pm25)
    future_pm10.append(next_pm10)
    for i in range(24, 1, -1):
        last_known[f"pm2.5lag{i}"] = last_known[f"pm2.5lag{i-1}"]
    last_known["pm2.5lag1"] = next_pm25
    for i in range(24, 1, -1):
        last_known[f"pm10lagP{i}"] = last_known[f"pm10lagP{i-1}"]
    last_known["pm10lagP1"] = next_pm10
    pm25_vals = [last_known[f"pm2.5lag{i}"].values[0] for i in range(1, 25)]
    pm10_vals = [last_known[f"pm10lagP{i}"].values[0] for i in range(1, 25)]
    last_known["pm2.5roll7"]  = sum(pm25_vals[:7]) / 7
    last_known["pm2.5roll14"] = sum(pm25_vals[:14]) / 14
    last_known["pm2.5roll21"] = sum(pm25_vals[:21]) / 21
    last_known["pm10roll7"]   = sum(pm10_vals[:7]) / 7
    last_known["pm10roll14"]  = sum(pm10_vals[:14]) / 14
    last_known["pm10roll21"]  = sum(pm10_vals[:21]) / 21

In [638]:
future_dates = pd.date_range(
    start=df["date"].iloc[-1] + pd.Timedelta(days=1),
    periods=10
)

In [639]:
forecast_10_days=pd.DataFrame(future_dates)

In [640]:
forecast_10_days.columns=["Date"]

In [641]:
forecast_10_days["pm25"]=pd.DataFrame(future_pm25)

In [642]:
forecast_10_days["pm10"]=pd.DataFrame(future_pm10)

In [643]:
forecast_10_days

        Date        pm25        pm10
0 2026-01-17  233.147512  283.990365
1 2026-01-18  228.773752  282.024640
2 2026-01-19  212.961152  273.361627
3 2026-01-20  189.845039  247.122724
4 2026-01-21  173.528862  228.881108
5 2026-01-22  162.544724  214.442202
6 2026-01-23  156.254887  210.276841
7 2026-01-24  152.042350  208.484372
8 2026-01-25  153.416471  209.957105
9 2026-01-26  156.908929  212.526718

In [644]:
forecast_10_days["AQI2.5"] = forecast_10_days["pm25"].apply(lambda x: aqi25(x, aqi_data))

In [645]:
forecast_10_days["AQI10"] = forecast_10_days["pm10"].apply(lambda x: aqi10(x, aqi_data))

In [646]:
forecast_10_days["AQI"] = forecast_10_days[["AQI2.5", "AQI10"]].max(axis=1)

In [647]:
forecast_10_days

        Date        pm25        pm10      AQI2.5       AQI10         AQI
0 2026-01-17  233.147512  283.990365  388.579187  283.990365  388.579187
1 2026-01-18  228.773752  282.024640  381.289587  282.024640  381.289587
2 2026-01-19  212.961152  273.361627  354.935253  273.361627  354.935253
3 2026-01-20  189.845039  247.122724  316.408398  247.122724  316.408398
4 2026-01-21  173.528862  228.881108  289.214770  228.881108  289.214770
5 2026-01-22  162.544724  214.442202  270.907873  214.442202  270.907873
6 2026-01-23  156.254887  210.276841  260.424812  210.276841  260.424812
7 2026-01-24  152.042350  208.484372  253.403916  208.484372  253.403916
8 2026-01-25  153.416471  209.957105  255.694119  209.957105  255.694119
9 2026-01-26  156.908929  212.526718  261.514882  212.526718  261.514882

In [566]:
import joblib
joblib.dump(rf_25, "rf_25.pkl")
joblib.dump(rf_10, "rf_10.pkl")

['rf_10.pkl']

In [651]:
features=X.columns.tolist()

In [653]:
df2_5={
    "ihi":[50,100,200,300,400,500],
    "ilo":[0,51,101,201,301,401],
    "bphi2.5":[30,60,90,120,250,550],
    "bplo2.5":[0,31,61,91,121,251]
}
df10={
    "ihi":[50,100,200,300,400,500],
    "ilo":[0,51,101,201,301,401],
    "bphipm10":[50,100,250,350,430,500],
    "bplopm10":[0,51,101,251,351,431]
}

In [654]:
joblib.dump(features, "features.pkl")
joblib.dump(df2_5, "aqi_pm25_table.pkl")
joblib.dump(df10, "aqi_pm10_table.pkl")

['aqi_pm10_table.pkl']